#!/usr/bin/env python3
"""Turns design/tokens.json into every output a consumer reads.

    design/tokens.json ──┬──▶ design/tokens.css                       (HTML prototypes)
                         └──▶ MyApp/DesignSystem/Generated/Tokens.swift
                              MyApp/DesignSystem/Generated/Colors.xcassets  (SwiftUI)

Roles keep one name across the three outputs: `text.on-action` is `--color-text-on-action`
in CSS, `DSColor.textOnAction` in Swift and the `DSTextOnAction` colour set in the catalog.
`.default` is dropped from the CSS variable (`--color-bg`, `--color-surface`), as the
prototypes' stylesheet expects. Run through `make tokens`; never edit the outputs.
"""

import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "tokens.json"
CSS_OUT = ROOT / "design" / "tokens.css"
SWIFT_DIR = ROOT / "MyApp" / "DesignSystem" / "Generated"
SWIFT_OUT = SWIFT_DIR / "Tokens.swift"
CATALOG = SWIFT_DIR / "Colors.xcassets"

POINTS_PER_REM = 16
ASSET_PREFIX = "DS"
HEADER = "GENERATED by Scripts/build-tokens.py from design/tokens.json. DO NOT EDIT: run `make tokens`."

# Token keys that are not valid Swift identifiers as written.
SWIFT_KEY_ALIASES = {"2xl": "xxl", "3xl": "xxxl"}


def css_var(role: str) -> str:
    """`text.on-action` -> `--color-text-on-action`; `bg.default` -> `--color-bg`."""
    parts = role.split(".")
    if parts[-1] == "default":
        parts = parts[:-1]
    if parts[0] == "dataviz":
        return "--" + "-".join(parts)
    return "--color-" + "-".join(parts)


def swift_name(role: str) -> str:
    """`text.on-action` -> `textOnAction`."""
    words = re.split(r"[.-]", role)
    return words[0] + "".join(w.capitalize() for w in words[1:])


def asset_name(role: str) -> str:
    """`text.on-action` -> `DSTextOnAction`."""
    name = swift_name(role)
    return ASSET_PREFIX + name[0].upper() + name[1:]


def swift_key(key: str) -> str:
    return SWIFT_KEY_ALIASES.get(key, key)


def parse_color(css: str):
    """Hex or rgba() to (r, g, b, a) in 0...1."""
    css = css.strip()
    hex_match = re.fullmatch(r"#([0-9a-fA-F]{6})", css)
    if hex_match:
        value = int(hex_match.group(1), 16)
        return ((value >> 16) / 255, ((value >> 8) & 0xFF) / 255, (value & 0xFF) / 255, 1.0)

    rgba_match = re.fullmatch(r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)", css)
    if rgba_match:
        r, g, b = (int(rgba_match.group(i)) / 255 for i in (1, 2, 3))
        a = float(rgba_match.group(4)) if rgba_match.group(4) else 1.0
        return (r, g, b, a)

    sys.exit(f"unsupported colour value: {css}")


def points(value: str) -> str:
    """`0.75rem` -> `12`, `12px` -> `12`."""
    match = re.fullmatch(r"([\d.]+)(rem|px)", value)
    if not match:
        sys.exit(f"unsupported dimension: {value}")
    number = float(match.group(1))
    if match.group(2) == "rem":
        number *= POINTS_PER_REM
    return number_literal(number)


def seconds(value: str) -> str:
    match = re.fullmatch(r"([\d.]+)ms", value)
    if not match:
        sys.exit(f"unsupported duration: {value}")
    return number_literal(float(match.group(1)) / 1000)


def em(value: str) -> str:
    match = re.fullmatch(r"(-?[\d.]+)(em)?", value)
    if not match:
        sys.exit(f"unsupported tracking: {value}")
    return number_literal(float(match.group(1)))


def number_literal(number: float) -> str:
    text = f"{number:.4f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-0") else "0"


def first_family(stack: str) -> str | None:
    """The first face of a CSS stack, or None when it is the platform's own font."""
    first = stack.split(",")[0].strip().strip("'\"")
    if first in ("-apple-system", "system-ui", "ui-monospace", "sans-serif", "monospace"):
        return None
    return first


def build_css(tokens: dict) -> str:
    lines = ["/*", f" * {HEADER}", " */", "", ":root {"]
    for group, values in tokens["font"].items():
        if isinstance(values, dict):
            for key, value in values.items():
                lines.append(f"  --font-{group}-{key}: {value};")
        else:
            lines.append(f"  --font-{group}: {values};")
    for section in ("space", "radius", "shadow"):
        for key, value in tokens[section].items():
            lines.append(f"  --{section}-{key}: {value};")
    for group, values in tokens["motion"].items():
        for key, value in values.items():
            lines.append(f"  --motion-{group}-{key}: {value};")
    lines.append("")
    for role, entry in tokens["color"].items():
        lines.append(f"  {css_var(role)}: {entry['light']};")
    lines.append("}")

    dark = [f"  {css_var(role)}: {entry['dark']};" for role, entry in tokens["color"].items()]
    lines += ["", "/* Dark theme: the explicit opt-in wins in both directions */", '[data-theme="dark"] {', *dark, "}"]
    lines += [
        "",
        "@media (prefers-color-scheme: dark) {",
        '  :root:not([data-theme="light"]) {',
        *["  " + line for line in dark],
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def doc(description: str | None, indent: str = "    ") -> list[str]:
    return [f"{indent}/// {description}"] if description else []


def build_swift(tokens: dict) -> str:
    out = [f"// {HEADER}", "", "import SwiftUI", ""]

    out += [
        "/// Semantic colour roles. Every value resolves a colour set in Colors.xcassets, so light",
        "/// and dark come from the catalog and follow the system appearance.",
        "enum DSColor {",
    ]
    for role, entry in tokens["color"].items():
        out += doc(entry.get("description"))
        out.append(f'    static let {swift_name(role)} = Color("{asset_name(role)}")')
        out.append("")
    out[-1] = "}"
    out.append("")

    out += ["/// Spacing scale in points.", "enum DSSpace {"]
    out += [f"    static let s{key}: CGFloat = {points(value)}" for key, value in tokens["space"].items()]
    out += ["}", ""]

    out += ["/// Corner radii in points.", "enum DSRadius {"]
    out += [f"    static let {swift_key(key)}: CGFloat = {points(value)}" for key, value in tokens["radius"].items()]
    out += ["}", ""]

    out += [
        f"/// Font sizes in points, converted from the rem source at {POINTS_PER_REM} pt per rem.",
        "///",
        "/// `DSTypography` maps roles to Dynamic Type text styles; these figures are for a custom",
        "/// face (`Font.custom(_:size:relativeTo:)`) and for `@ScaledMetric` dimensions.",
        "enum DSFontSize {",
    ]
    out += [f"    static let {swift_key(key)}: CGFloat = {points(value)}" for key, value in tokens["font"]["size"].items()]
    out += ["}", ""]

    out += ["/// Line heights as a multiplier of the font size.", "enum DSLineHeight {"]
    out += [f"    static let {swift_key(key)}: Double = {number_literal(float(value))}" for key, value in tokens["font"]["line-height"].items()]
    out += ["}", ""]

    out += ["/// Letter spacing as a fraction of the font size.", "enum DSTracking {"]
    out += [f"    static let {swift_key(key)}: Double = {em(value)}" for key, value in tokens["font"]["tracking"].items()]
    out += ["}", ""]

    out += [
        "/// First family of each stack, `nil` when the stack starts with the platform font.",
        "/// A custom face has to be bundled and registered in `UIAppFonts` as well.",
        "enum DSFontFamily {",
    ]
    for key, stack in tokens["font"]["family"].items():
        family = first_family(stack)
        literal = f'"{family}"' if family else "nil"
        out.append(f"    static let {key}: String? = {literal}")
    out += ["}", ""]

    out += ["/// Durations in seconds and stagger steps, from the motion tokens.", "enum DSMotion {"]
    out += [f"    static let duration{key}: Double = {seconds(value)}" for key, value in tokens["motion"]["duration"].items()]
    out.append("")
    out += [f"    static let stagger{key}: Double = {seconds(value)}" for key, value in tokens["motion"]["stagger"].items()]
    out += ["}", ""]

    dataviz = [swift_name(role) for role in tokens["color"] if role.startswith("dataviz.")]
    out += [
        "/// The categorical palette, in order of use.",
        "enum DSDataViz {",
        "    static let palette: [Color] = [",
        *[f"        DSColor.{name}," for name in dataviz],
        "    ]",
        "}",
        "",
    ]
    return "\n".join(out)


def component(value: float) -> str:
    return f"{value:.3f}"


def color_entry(css: str, appearance: str | None) -> dict:
    r, g, b, a = parse_color(css)
    entry = {
        "color": {
            "color-space": "srgb",
            "components": {"alpha": component(a), "blue": component(b), "green": component(g), "red": component(r)},
        },
        "idiom": "universal",
    }
    if appearance:
        entry = {"appearances": [{"appearance": "luminosity", "value": appearance}], **entry}
    return entry


def build_catalog(tokens: dict) -> int:
    if CATALOG.exists():
        shutil.rmtree(CATALOG)
    CATALOG.mkdir(parents=True)
    info = {"info": {"author": "xcode", "version": 1}}
    (CATALOG / "Contents.json").write_text(json.dumps(info, indent=2) + "\n")

    for role, entry in tokens["color"].items():
        folder = CATALOG / f"{asset_name(role)}.colorset"
        folder.mkdir()
        contents = {
            "colors": [color_entry(entry["light"], None), color_entry(entry["dark"], "dark")],
            **info,
        }
        (folder / "Contents.json").write_text(json.dumps(contents, indent=2) + "\n")
    return len(tokens["color"])


def main() -> None:
    tokens = json.loads(SOURCE.read_text())
    CSS_OUT.write_text(build_css(tokens))
    SWIFT_DIR.mkdir(parents=True, exist_ok=True)
    SWIFT_OUT.write_text(build_swift(tokens))
    count = build_catalog(tokens)
    print(f"tokens: {CSS_OUT.relative_to(ROOT)}, {SWIFT_OUT.relative_to(ROOT)}, {count} colour sets")


if __name__ == "__main__":
    main()
